# Generated by Django 5.1.2 on 2024-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author'), ('user', 'User')], max_length=15),
        ),
    ]
